server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Proxy /api/* e /agent/* para o controller
    location /api/ {
        proxy_pass http://controller:8080;
        proxy_set_header Host $host;
    }

    location /agent/ {
        proxy_pass http://controller:8080;
        proxy_set_header Host $host;
    }

    # React Router — todas as rotas caem no index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
